// 统一错误码与构造助手（可逐步全项目迁移）
export const ERROR_CODES = {
  INBOND_AGENT_ID_MISSING: "INBOND_AGENT_ID_MISSING",
  INBOND_CLEARANCE_TYPE_INVALID: "INBOND_CLEARANCE_TYPE_INVALID",
  INBOND_SHIPPING_TYPE_INVALID: "INBOND_SHIPPING_TYPE_INVALID",
  INBOND_TAX_TYPE_INVALID: "INBOND_TAX_TYPE_INVALID",
  INBOND_NOT_FOUND: "INBOND_NOT_FOUND",
  INBOND_NOT_MODIFIABLE: "INBOND_NOT_MODIFIABLE",
  INBOND_NOT_DRAFT: "INBOND_NOT_DRAFT",
  INBOND_NO_PACKAGES: "INBOND_NO_PACKAGES",
  INBOND_PACKAGE_MISSING_REQUIREMENT: "INBOND_PACKAGE_MISSING_REQUIREMENT",
  INBOND_SUBMIT_FAILED: "INBOND_SUBMIT_FAILED",
  INBOND_CREATE_FAILED: "INBOND_CREATE_FAILED",
  INBOND_UPDATE_FAILED: "INBOND_UPDATE_FAILED",
  // 客户相关
  CUSTOMER_CREATE_INVALID_INPUT: "CUSTOMER_CREATE_INVALID_INPUT",
  CUSTOMER_ACCOUNT_EXISTS: "CUSTOMER_ACCOUNT_EXISTS",
  CUSTOMER_EMAIL_EXISTS: "CUSTOMER_EMAIL_EXISTS",
  CUSTOMER_CREATE_FAILED: "CUSTOMER_CREATE_FAILED",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  CUSTOMER_UPDATE_FAILED: "CUSTOMER_UPDATE_FAILED",
  CUSTOMER_DISABLE_FAILED: "CUSTOMER_DISABLE_FAILED",
  CUSTOMER_ENABLE_FAILED: "CUSTOMER_ENABLE_FAILED",
  CUSTOMER_PASSWORD_RESET_FAILED: "CUSTOMER_PASSWORD_RESET_FAILED",
  CUSTOMER_IMPORT_FAILED: "CUSTOMER_IMPORT_FAILED",
  CUSTOMER_RATE_LIMIT: "CUSTOMER_RATE_LIMIT",
  // 权限 & 校验
  PERMISSION_DENIED: "PERMISSION_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  // 通用
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
};

export function buildError(code, message, extra = {}) {
  return { success: false, code, message, ...extra };
}
