// 统一错误码与构造助手（可逐步全项目迁移）
export const ERROR_CODES = {
  INBOND_AGENT_ID_MISSING: "INBOND_AGENT_ID_MISSING",
  INBOND_CLEARANCE_TYPE_INVALID: "INBOND_CLEARANCE_TYPE_INVALID",
  INBOND_SHIPPING_TYPE_INVALID: "INBOND_SHIPPING_TYPE_INVALID",
  INBOND_TAX_TYPE_INVALID: "INBOND_TAX_TYPE_INVALID",
  INBOND_NOT_FOUND: "INBOND_NOT_FOUND",
  INBOND_NOT_MODIFIABLE: "INBOND_NOT_MODIFIABLE",
  INBOND_NOT_DRAFT: "INBOND_NOT_DRAFT",
  INBOND_NO_PACKAGES: "INBOND_NO_PACKAGES",
  INBOND_PACKAGE_MISSING_REQUIREMENT: "INBOND_PACKAGE_MISSING_REQUIREMENT",
  INBOND_SUBMIT_FAILED: "INBOND_SUBMIT_FAILED",
  INBOND_CREATE_FAILED: "INBOND_CREATE_FAILED",
  INBOND_UPDATE_FAILED: "INBOND_UPDATE_FAILED",
  INBOND_ARRIVE_INVALID_STATUS: "INBOND_ARRIVE_INVALID_STATUS",
  INBOND_ARRIVE_FAILED: "INBOND_ARRIVE_FAILED",

  // 客户相关
  CUSTOMER_CREATE_INVALID_INPUT: "CUSTOMER_CREATE_INVALID_INPUT",
  CUSTOMER_ACCOUNT_EXISTS: "CUSTOMER_ACCOUNT_EXISTS",
  CUSTOMER_EMAIL_EXISTS: "CUSTOMER_EMAIL_EXISTS",
  CUSTOMER_CREATE_FAILED: "CUSTOMER_CREATE_FAILED",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  CUSTOMER_UPDATE_FAILED: "CUSTOMER_UPDATE_FAILED",
  CUSTOMER_DISABLE_FAILED: "CUSTOMER_DISABLE_FAILED",
  CUSTOMER_ENABLE_FAILED: "CUSTOMER_ENABLE_FAILED",
  CUSTOMER_PASSWORD_RESET_FAILED: "CUSTOMER_PASSWORD_RESET_FAILED",
  CUSTOMER_IMPORT_FAILED: "CUSTOMER_IMPORT_FAILED",
  CUSTOMER_RATE_LIMIT: "CUSTOMER_RATE_LIMIT",

  // 包裹（Agent）
  PKG_CODE_MISSING: "PKG_CODE_MISSING",
  PKG_SCAN_BUSY: "PKG_SCAN_BUSY",
  PKG_NOT_FOUND: "PKG_NOT_FOUND",
  PKG_AGENT_FORBIDDEN: "PKG_AGENT_FORBIDDEN",
  PKG_STATUS_INVALID: "PKG_STATUS_INVALID",
  PKG_RECEIVE_ERROR: "PKG_RECEIVE_ERROR",
  PKG_CODE_LIST_EMPTY: "PKG_CODE_LIST_EMPTY",
  PKG_CODE_LIST_TOO_LARGE: "PKG_CODE_LIST_TOO_LARGE",
  PKG_BATCH_ALL_FAILED: "PKG_BATCH_ALL_FAILED",
  PKG_BATCH_RECEIVE_ERROR: "PKG_BATCH_RECEIVE_ERROR",

  // 预报（Agent）
  FORECAST_CREATE_FAILED: "FORECAST_CREATE_FAILED",
  FORECAST_MAWB_UPDATE_FAILED: "FORECAST_MAWB_UPDATE_FAILED",
  FORECAST_LIST_FAILED: "FORECAST_LIST_FAILED",
  FORECAST_NOT_FOUND: "FORECAST_NOT_FOUND",
  FORECAST_DETAIL_FAILED: "FORECAST_DETAIL_FAILED",
  FORECAST_TRANSITION_TARGET_REQUIRED: "FORECAST_TRANSITION_TARGET_REQUIRED",
  FORECAST_TRANSITION_BUSY: "FORECAST_TRANSITION_BUSY",
  FORECAST_TRANSITION_INVALID: "FORECAST_TRANSITION_INVALID",
  FORECAST_NOT_DRAFT: "FORECAST_NOT_DRAFT",
  FORECAST_NO_PACKAGES: "FORECAST_NO_PACKAGES",
  FORECAST_SUBMIT_FAILED: "FORECAST_SUBMIT_FAILED",
  FORECAST_NOT_BOOKED: "FORECAST_NOT_BOOKED",
  FORECAST_ASSIGN_HAWB_FAILED: "FORECAST_ASSIGN_HAWB_FAILED",
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  NO_PACKAGES_FOR_CLIENT: "NO_PACKAGES_FOR_CLIENT",
  FORECAST_BATCH_HAWB_FAILED: "FORECAST_BATCH_HAWB_FAILED",
  INVALID_ASSIGNMENTS: "INVALID_ASSIGNMENTS",
  FORECAST_CLEARANCE_INVALID: "FORECAST_CLEARANCE_INVALID",
  FORECAST_CLEARANCE_BUSY: "FORECAST_CLEARANCE_BUSY",
  FORECAST_CLEARANCE_FAILED: "FORECAST_CLEARANCE_FAILED",

  // 权限 & 校验
  PERMISSION_DENIED: "PERMISSION_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",

  // 其他
  OPREQ_BIND_NOT_IMPLEMENTED: "OPREQ_BIND_NOT_IMPLEMENTED",

  // 通用
  UNKNOWN_ERROR: "UNKNOWN_ERROR",

  // 包裹/操作需求权限
  PKG_REQUIREMENT_NOT_ALLOWED: "PKG_REQUIREMENT_NOT_ALLOWED",
  // Inbond 提交校验
  INBOND_PACKAGE_MISSING_ITEMS: "INBOND_PACKAGE_MISSING_ITEMS",
};

export function buildError(code, message, extra = {}) {
  return { success: false, code, message, ...extra };
}
