export default (sequelize, DataTypes) => {
  const FtzInventoryLedger = sequelize.define(
    "FtzInventoryLedger",
    {
      id: { type: DataTypes.BIGINT, autoIncrement: true, primaryKey: true },
      direction: {
        type: DataTypes.ENUM(
          "inbound",
          "outbound",
          "adjustment",
          "reversal",
          "internal_move"
        ),
        allowNull: false,
        comment: "记录方向",
      },
      delivery_order_id: { type: DataTypes.BIGINT, allowNull: true },
      pallet_id: { type: DataTypes.BIGINT, allowNull: true },
      package_id: { type: DataTypes.BIGINT, allowNull: true },
      forecast_id: { type: DataTypes.BIGINT, allowNull: true },
      customer_id: { type: DataTypes.BIGINT, allowNull: true },
      warehouse_id: { type: DataTypes.BIGINT, allowNull: true },
      tenant_id: { type: DataTypes.BIGINT, allowNull: true },
      mawb: { type: DataTypes.STRING(32), allowNull: true },
      hawb: { type: DataTypes.STRING(64), allowNull: true },
      do_number: { type: DataTypes.STRING(32), allowNull: true },
      reference_no: { type: DataTypes.STRING(64), allowNull: true },
      customs_entry_no: { type: DataTypes.STRING(64), allowNull: true },
      batch_no: { type: DataTypes.STRING(64), allowNull: true },
      sku_code: { type: DataTypes.STRING(64), allowNull: true },
      hs_code: { type: DataTypes.STRING(32), allowNull: true },
      goods_name_cn: { type: DataTypes.STRING(255), allowNull: true },
      goods_name_en: { type: DataTypes.STRING(255), allowNull: true },
      origin_country: { type: DataTypes.STRING(8), allowNull: true },
      lot_no: { type: DataTypes.STRING(64), allowNull: true },
      serial_no: { type: DataTypes.STRING(128), allowNull: true },
      brand: { type: DataTypes.STRING(128), allowNull: true },
      model: { type: DataTypes.STRING(128), allowNull: true },
      qty: {
        type: DataTypes.DECIMAL(18, 6),
        allowNull: false,
        defaultValue: 0,
      },
      uom: { type: DataTypes.STRING(16), allowNull: true },
      secondary_qty: { type: DataTypes.DECIMAL(18, 6), allowNull: true },
      secondary_uom: { type: DataTypes.STRING(16), allowNull: true },
      gross_weight_kg: { type: DataTypes.DECIMAL(18, 3), allowNull: true },
      net_weight_kg: { type: DataTypes.DECIMAL(18, 3), allowNull: true },
      volume_cbm: { type: DataTypes.DECIMAL(18, 3), allowNull: true },
      declared_value: { type: DataTypes.DECIMAL(18, 2), allowNull: true },
      currency: { type: DataTypes.STRING(8), allowNull: true },
      exchange_rate: { type: DataTypes.DECIMAL(18, 6), allowNull: true },
      bond_status: {
        type: DataTypes.STRING(16),
        allowNull: true,
        comment: "bonded / non_bonded",
      },
      customs_status: { type: DataTypes.STRING(32), allowNull: true },
      ledger_status: { type: DataTypes.STRING(16), defaultValue: "active" },
      inbound_time: { type: DataTypes.DATE, allowNull: true },
      outbound_time: { type: DataTypes.DATE, allowNull: true },
      operator_id: { type: DataTypes.BIGINT, allowNull: true },
      operator_name: { type: DataTypes.STRING(100), allowNull: true },
      source_action: { type: DataTypes.STRING(64), allowNull: true },
      zone_code: { type: DataTypes.STRING(32), allowNull: true },
      warehouse_location: { type: DataTypes.STRING(64), allowNull: true },
      area_type: { type: DataTypes.STRING(32), allowNull: true },
      danger_class: { type: DataTypes.STRING(32), allowNull: true },
      temperature_range: { type: DataTypes.STRING(32), allowNull: true },
      expiry_date: { type: DataTypes.DATE, allowNull: true },
      manufacturer: { type: DataTypes.STRING(255), allowNull: true },
      revision: { type: DataTypes.INTEGER, defaultValue: 1 },
      reversal_of: {
        type: DataTypes.BIGINT,
        allowNull: true,
        comment: "被冲销记录ID",
      },
      prev_hash: { type: DataTypes.STRING(128), allowNull: true },
      hash: { type: DataTypes.STRING(128), allowNull: true },
      unique_key: { type: DataTypes.STRING(128), allowNull: true },
    },
    {
      tableName: "ftz_inventory_ledger",
      timestamps: true,
      createdAt: "created_at",
      updatedAt: "updated_at",
      indexes: [
        { fields: ["direction"] },
        { fields: ["delivery_order_id"] },
        { fields: ["pallet_id"] },
        { fields: ["package_id"] },
        { fields: ["warehouse_id"] },
        { fields: ["tenant_id"] },
        { fields: ["mawb"] },
        { fields: ["hawb"] },
        { fields: ["hs_code"] },
        { fields: ["unique_key"], unique: false },
        { fields: ["created_at"] },
      ],
    }
  );

  return FtzInventoryLedger;
};
